version: '2'
services:

  cow:
    build: ./src/ws-cow
    image: cow-ws
    container_name: cowcon
    ports:
    - "80:5000"

  fortune:
    build: ./src/ws-fort
    image: fortune-ws
    container_name: fortcon
    ports:
    - "5001:5000"

  date:
    build: ./src/ws-date
    image: date-ws
    container_name: datecon
    ports:
    - "5002:5000"

