apiVersion: v1
kind: Service
metadata:
  labels:
    app: &name cowcon
  name: *name
spec:
  type: NodePort
  ports:
  - name: listener
    port: 80
    targetPort: 5000
  externalIPs:
  - 10.0.2.15	
  selector:
    app: *name
