apiVersion: v1
kind: Service
metadata:
  labels:
    app: &name datecon
  name: *name
spec:
  type: ClusterIP
  ports:
  - name: listener
    port: 5000
    targetPort: 5000
  selector:
    app: *name
